
import React from 'react';
import {Table,Icon, Card} from 'antd';
import API from '../utils/API';
import Menu from '../menu.pdf'
const columns=[
  {
    width:150,
    title: 'Component',
    dataIndex: 'component',
    key: 'component',
    defaultSortOrder: 'ascend',
    sorter: (a, b) => {return a.component.localeCompare(b.component)},
  },
  {
    width:100,
    title: 'Number',
    dataIndex: 'number',
    key: 'number',
    defaultSortOrder: 'ascend',
    sorter: (a, b) => {return a.component.localeCompare(b.component)},
    render: text => <a target= "_blank" rel="noopener noreferrer" href={"https://carnival.atlassian.net/browse/"+text}>{text}</a>
  },
  {
    width:200,
    title: 'Title',
    dataIndex: 'title',
    key: 'title',
  },
  {
    width:200,
    title: 'State',
    dataIndex: 'state',
    key: 'state',
    filters:[{
      text:"DEV COMPLETE",
      value:"DEV COMPLETE"
    },
    {
      text:"QA IN PROGRESS",
      value: "QA IN PROGRESS"
    },
    {
      text: "BLOCKED",
      value: "BLOCKED"
    },{
      text:'IN PROGRESS',
      value:'IN PROGRESS'
    }],
    filterMultiple: true,
    onFilter: (value, record) => record.state.indexOf(value) === 0,
    // defaultSortOrder: 'ascend',
    // sorter: (a, b) => {return a.state.localeCompare(b.state)},
  },
  {
    width:200,
    title: 'Status',
    dataIndex: 'status',
    key: 'status'
  }
];
const dataSource = [
  
  {
    key:'1',
    component:'xiOrchistrate',
    number:'MGLN-7272',
    state:'BLOCKED',
    title:'[XOS] v2 folio, add support for new fields generated by lodging task',
    status:'UP-66'
  },
  {
    key:'2',
    component:'Ocean.com',
    number: 'MGLN-7288',
    state: 'QA IN PROGRESS',
    title: 'Ocean.com - Journey - Add Companions to a Journey',
    status:'Looking at this today'
  },
  {
    key:'3',
    component:'OceanView: Android, OceanView: iOS',
    number:'MGLN-7181',
    state:'BLOCKED',
    title:'OceanView Mobile - Closed Captions - Subtitles',
    status:'Waiting for 2.60.1 to be in devint'
  },
  {
    key:'4',
    component:'Ocean.com',
    number: 'MGLN-7286',
    state: 'QA IN PROGRESS',
    title: 'Ocean.com - Journey - Travel Companions Landing Page',
    status:'Looking at this today'
  },
  {
    key:'5',
    component: 'xiOrchistrate',
    number:'MGLN-7606',
    state: 'QA IN PROGRESS',
    title: 'Payload modification request on xos/companions/extende',
    status: 'Looking at this today'
  },
  {
    key:'6',
    component: 'xiImmigration',
    number: 'MGLN-7597',
    state: 'QA IN PROGRESS',
    title: '[Dive-Traveldoc-Recommendation] New destination codes added on journey details of code "HTL", breaking TDRS because not a valid port code.',
    status: 'Looking at this today..'
  },
  {
    key:'7',
    component: 'xiImmigration',
    number: 'MGLN-7572',
    state: 'QA IN PROGRESS',
    title: '(DM-8723) Personal Details "birth-country-code" not being saved',
    status: 'Looking at this today..'
  },
  {
    key:'8',
    component:'Ocean.com',
    number: 'MGLN-7556',
    state: 'QA IN PROGRESS',
    title: 'Ocean.com Add API integration for Companions to companion selector',
    status: 'Looking at this today..'
  },
  {
    key:'9',
    component:'Ocean.com',
    number: 'MGLN-7312',
    state: 'QA IN PROGRESS',
    title: 'OceanReady - OceanReady Checklist - Companion Checklist',
    status: 'Looking at this today..'
  },
  {
    key:'10',
    component: 'Ocean.com',
    state: 'QA IN PROGRESS',
    number:'MGLN-7282',
    title: 'Ocean.com - Journey - Travel Pass (QR Code) Print and Email',
    status: 'Looking at this today'
  },
  {
    key:'11',
    component: 'Ocean.com',
    number:'MGLN-7274',
    state: 'QA IN PROGRESS',
    title: 'Ocean.com - Journey - Finding an Exisiting Journey',
    status: 'Looking at this today'
  }

];

let now = new Date(2018, 7, 21, 12, 0);
let lastupdated = now.toDateString() + " - " + now.toLocaleTimeString();
class Main extends React.Component {
  // componentDidMount(){
    
  //   API.getMyOpenIssues().then((data) => {
  //     alert(JSON.stringify(data.response))
  //   },(error)=>{
  //     alert(JSON.stringify(error.errorMessages));
  //   });
  // }
    render() {
      return (
        <div>
            
            <Card title={<div>Ticket Status   <Icon type="line-chart"/> <br/><strong>Last Updated:</strong>  {lastupdated}</div>}  >
            
              <Table dataSource={dataSource} columns={columns} size="small" scroll={{ x: 800 }}/>
            </Card>
            <br/>
            <br/>
            <Card title={<div>Notes <Icon type="edit"/></div>}>
              <Card>
                <ul>
                    <li><a target="_blank" rel="noopener noreferrer" href="https://carnival.atlassian.net/wiki/spaces/MGLN/pages/157278542/QA+ticket+validation+tracking">QA Ticket Validation Tracking</a></li>
                    <li><a target="_blank" rel="noopener noreferrer" href="https://carnival.atlassian.net/issues/?filter=40237">Open issues assigned To Me</a></li>
                    <li><a target="_blank" rel="noopener noreferrer" href="http://10.127.193.99/xiaccess/inventory">Door Panel Inventory (be on DPA wifi)</a></li>
                    <li><a target="_blank" rel="noopener noreferrer" href={Menu}>Lunch</a></li>
                </ul>
                
              </Card>
              <br/>
              <Card title={<div>Priorities <Icon type="profile"/></div>}>
                <ol>
                  <li>Tickets</li>
                  <li>Optimizing mocha/TR script</li>
                </ol>
              </Card>
            </Card>
        </div>
      );
    }
  }
 
export {Main};
export default Main;
  
